import { useState, useCallback, useEffect, useRef } from "react";

// ─── PRE-RECORDED AI DEMO PAIRS ─────────────────────────────────────────────
// Generated by Claude using only the schema as context.
// No custom instructions, no examples, no tool definitions.
const DEMO_PAIRS = [
  {
    prompt: "Schedule a product launch announcement to Instagram and LinkedIn for next Tuesday at 2pm UTC",
    output: `mutation($input: CreatePostsInput!) {
  createPosts(input: $input) {
    success
    results {
      success
      post {
        id
        status
        scheduledAt
        profile {
          channel
          username
        }
      }
      error
    }
  }
}

# Variables:
# {
#   "input": {
#     "posts": [
#       {
#         "profileId": "prof_ig_001",
#         "text": "It's here! 🚀 We're thrilled to announce our new product. Link in bio for details. #launch #newproduct",
#         "scheduledAt": "2025-04-08T14:00:00Z"
#       },
#       {
#         "profileId": "prof_li_002",
#         "text": "I'm excited to share that we've officially launched our new product today. After months of development and feedback from our community, we built something that solves a real problem.",
#         "scheduledAt": "2025-04-08T14:00:00Z"
#       }
#     ]
#   }
# }`,
  },
  {
    prompt: "Show me my top 5 posts from last week ranked by engagement",
    output: `query {
  posts(
    status: SENT
    scheduledAfter: "2025-03-31"
    scheduledBefore: "2025-04-07"
    sortBy: ENGAGEMENT_DESC
    limit: 5
  ) {
    edges {
      node {
        id
        text
        sentAt
        profile {
          channel
          username
        }
        analytics {
          impressions
          likes
          comments
          shares
          clicks
        }
      }
    }
    totalCount
  }
}`,
  },
  {
    prompt: "Set up a webhook to notify me when posts fail or get comments",
    output: `mutation {
  createWebhook(input: {
    url: "https://myapp.com/webhooks/buffer"
    events: [POST_FAILED, COMMENT_RECEIVED]
  }) {
    success
    webhook {
      id
      url
      events
      enabled
      secret
      createdAt
    }
    error
  }
}`,
  },
  {
    prompt: "Get all my profiles and check which ones are disconnected",
    output: `query {
  profiles {
    id
    channel
    name
    username
    isConnected
    timezone
  }
}`,
  },
  {
    prompt: "Find all draft posts tagged with our Q1 campaign and add them to the queue",
    output: `# Step 1: Find all draft posts with the Q1 campaign tag
query {
  posts(status: DRAFT, tagId: "tag_q1_campaign") {
    edges {
      node {
        id
        text
        profile {
          channel
          username
        }
        tags {
          name
        }
      }
    }
    totalCount
  }
}

# Step 2: For each post ID returned, add it to the queue
mutation {
  addToQueue(id: "post_001") {
    success
    post {
      id
      status
      scheduledAt
    }
    error
  }
}`,
  },
  {
    prompt: "Check my rate limit then get analytics for all profiles this quarter",
    output: `# Step 1: Check rate limit budget before batch operation
query {
  rateLimit {
    limit
    remaining
    resetsAt
    windowSeconds
  }
}

# Step 2: Get quarterly analytics for all profiles
query {
  profiles {
    id
    channel
    username
    analytics(period: QUARTER) {
      followers
      followersChange
      postCount
      impressions
      totalEngagement
      engagementRate
      periodStart
      periodEnd
    }
  }
}`,
  },
  {
    prompt: "Reply to a customer comment thanking them for their feedback",
    output: `# Step 1: Get recent unreplied comments
query {
  comments(postId: "post_xyz789", limit: 10) {
    edges {
      node {
        id
        text
        authorName
        createdAt
        isReplied
      }
    }
    totalCount
  }
}

# Step 2: Reply to the specific comment
mutation {
  replyToComment(
    commentId: "comment_abc123"
    text: "Thank you so much for the kind words! We really appreciate your support. 💛"
  ) {
    success
    error
  }
}`,
  },
  {
    prompt: "Set my Instagram to post Monday/Wednesday/Friday at 9am and noon",
    output: `mutation {
  updateSchedule(input: {
    profileId: "prof_ig_001"
    schedules: [
      {
        days: ["monday", "wednesday", "friday"]
        times: ["09:00", "12:00"]
      }
    ]
  }) {
    success
    profile {
      channel
      username
      schedules {
        days
        times
      }
    }
    error
  }
}`,
  },
];

// ─── DOCS CONTENT ────────────────────────────────────────────────────────────
const DOCS = {
  quickstart: {
    title: "Quickstart",
    subtitle: "Zero to first API call in 5 minutes",
    sections: [
      {
        heading: "Install the SDK",
        body: "The Buffer SDK handles authentication, retries, and rate limiting. Install it and initialize with your access token.",
        code: `npm install @buffer/sdk`,
        lang: "bash",
      },
      {
        heading: "Hello, Buffer",
        body: "Three lines to verify your connection. This lists every social account linked to your Buffer workspace.",
        code: `import { Buffer } from "@buffer/sdk";

const buffer = new Buffer({ accessToken: process.env.BUFFER_TOKEN });
const profiles = await buffer.profiles.list();

console.log(profiles.map(p => \`\${p.channel}: @\${p.username}\`));
// → ["instagram: @mybrand", "linkedin: @mybrand", "x: @mybrand"]`,
        lang: "javascript",
      },
      {
        heading: "Or Use the GraphQL API Directly",
        body: "Prefer raw GraphQL? Every SDK method maps 1:1 to the schema. Here's the same call in JavaScript, Python, and curl.",
        code: `const response = await fetch("https://api.buffer.com/graphql", {
  method: "POST",
  headers: {
    "Authorization": "Bearer YOUR_ACCESS_TOKEN",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query: \`{ profiles { id channel name username isConnected } }\`,
  }),
});

const { data } = await response.json();
console.log(data.profiles);`,
        lang: "javascript",
      },
      {
        heading: null,
        body: null,
        code: `import requests

response = requests.post(
    "https://api.buffer.com/graphql",
    headers={
        "Authorization": "Bearer YOUR_ACCESS_TOKEN",
        "Content-Type": "application/json",
    },
    json={"query": "{ profiles { id channel name username isConnected } }"},
)

profiles = response.json()["data"]["profiles"]
print(profiles)`,
        lang: "python",
      },
      {
        heading: null,
        body: null,
        code: `curl -X POST https://api.buffer.com/graphql \\
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"query": "{ profiles { id channel name username isConnected } }"}'`,
        lang: "curl",
      },
      {
        heading: "Create & Schedule a Post",
        body: "Include scheduledAt to queue it. Omit it to save as a draft. Always check the success and error fields.",
        code: `const response = await fetch("https://api.buffer.com/graphql", {
  method: "POST",
  headers: {
    "Authorization": "Bearer YOUR_ACCESS_TOKEN",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query: \`mutation($input: CreatePostInput!) {
      createPost(input: $input) {
        success
        post { id status scheduledAt }
        error
      }
    }\`,
    variables: {
      input: {
        profileId: "prof_abc123",
        text: "Excited to share what we've been working on! 🚀",
        scheduledAt: "2025-04-01T14:30:00Z",
      },
    },
  }),
});

const { data } = await response.json();
console.log(data.createPost.post);`,
        lang: "javascript",
      },
      {
        heading: null,
        body: null,
        code: `response = requests.post(
    "https://api.buffer.com/graphql",
    headers={
        "Authorization": "Bearer YOUR_ACCESS_TOKEN",
        "Content-Type": "application/json",
    },
    json={
        "query": """mutation($input: CreatePostInput!) {
            createPost(input: $input) {
                success
                post { id status scheduledAt }
                error
            }
        }""",
        "variables": {
            "input": {
                "profileId": "prof_abc123",
                "text": "Excited to share what we've been working on! 🚀",
                "scheduledAt": "2025-04-01T14:30:00Z"
            }
        }
    },
)

print(response.json()["data"]["createPost"])`,
        lang: "python",
      },
      {
        heading: "Post to Multiple Channels",
        body: "Use createPosts (plural) to publish across platforms in one call. Customize the text for each channel's audience and character limits.",
        code: `const response = await fetch("https://api.buffer.com/graphql", {
  method: "POST",
  headers: {
    "Authorization": "Bearer YOUR_ACCESS_TOKEN",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query: \`mutation($input: CreatePostsInput!) {
      createPosts(input: $input) {
        success
        results {
          success
          post { id profile { channel } status }
          error
        }
      }
    }\`,
    variables: {
      input: {
        posts: [
          {
            profileId: "prof_ig_001",
            text: "New feature alert! 🎉 Link in bio for details.",
            scheduledAt: "2025-04-01T14:30:00Z",
          },
          {
            profileId: "prof_li_002",
            text: "We just shipped a feature that changes how teams collaborate on content. Here's what it does and why it matters.",
            scheduledAt: "2025-04-01T14:30:00Z",
          },
        ],
      },
    },
  }),
});

const { data } = await response.json();
data.createPosts.results.forEach(r =>
  console.log(r.post.profile.channel, r.success)
);`,
        lang: "javascript",
      },
      {
        heading: "Set Up Webhooks",
        body: "Instead of polling (which ate the old API's 60 req/min budget), register a webhook and get notified in real time when posts publish, fail, or receive comments.",
        code: `const response = await fetch("https://api.buffer.com/graphql", {
  method: "POST",
  headers: {
    "Authorization": "Bearer YOUR_ACCESS_TOKEN",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query: \`mutation {
      createWebhook(input: {
        url: "https://myapp.com/webhooks/buffer"
        events: [POST_SENT, POST_FAILED, COMMENT_RECEIVED]
      }) {
        success
        webhook { id secret events }
        error
      }
    }\`,
  }),
});

const { data } = await response.json();
// Save the secret for verifying webhook signatures
console.log("Webhook secret:", data.createWebhook.webhook.secret);`,
        lang: "javascript",
      },
    ],
  },
  errors: {
    title: "Error Reference",
    subtitle: "Every error you'll encounter, with response bodies and fixes",
    sections: [
      {
        heading: "How Errors Work in GraphQL",
        body: "Unlike REST, GraphQL returns 200 OK for most responses. You'll see two kinds of errors: GraphQL-level (malformed query) in a top-level errors array, and application-level (operation failed) in the mutation's error field. Always check both.",
        code: `const result = await response.json();

// GraphQL-level errors
if (result.errors) {
  console.error("Query error:", result.errors[0].message);
  return;
}

// Application-level errors
if (!result.data.createPost.success) {
  console.error("Failed:", result.data.createPost.error);
  return;
}`,
        lang: "javascript",
      },
      {
        heading: "Text Exceeds Character Limit",
        body: "Each channel has a different limit. The error tells you exactly how long your text is and what the limit is. Validate client-side using the Channel enum descriptions.",
        code: `{
  "data": {
    "createPost": {
      "success": false,
      "post": null,
      "error": "Text exceeds maximum length for X (280 characters). Your text is 314 characters."
    }
  }
}`,
        lang: "json",
      },
      {
        heading: "Profile Disconnected",
        body: "The social media token expired or was revoked. Check profile.isConnected before posting. Subscribe to the PROFILE_CONNECTION_CHANGED webhook to detect this proactively.",
        code: `{
  "data": {
    "createPost": {
      "success": false,
      "post": null,
      "error": "Profile prof_abc123 is disconnected. The user must reauthorize this profile in Buffer."
    }
  }
}`,
        lang: "json",
      },
      {
        heading: "Rate Limited (429)",
        body: "Read X-RateLimit-Remaining on every response and throttle before you hit zero. The Retry-After header tells you when to resume. Use webhooks instead of polling.",
        code: `HTTP/1.1 429 Too Many Requests
X-RateLimit-Limit: 300
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 2025-04-01T14:35:00Z
Retry-After: 47

{
  "error": "rate_limit_exceeded",
  "message": "Rate limit exceeded. Try again in 47 seconds."
}`,
        lang: "http",
      },
      {
        heading: "Duplicate Content",
        body: "Social platforms penalize duplicate posts. Buffer prevents them at the API level within a 24-hour window.",
        code: `{
  "data": {
    "createPost": {
      "success": false,
      "post": null,
      "error": "This content was recently posted to this profile. Duplicate posts within 24 hours are not allowed."
    }
  }
}`,
        lang: "json",
      },
    ],
  },
  workflows: {
    title: "Common Workflows",
    subtitle: "Integration patterns for the most frequent use cases",
    sections: [
      {
        heading: "Content Calendar: Schedule a Week",
        body: "Get your profiles and their schedules, batch-create posts matched to time slots, then verify the queue. A typical three-step pattern for small businesses.",
        code: `# Step 1: Get profiles & schedules
query { profiles { id channel schedules { days times } } }

# Step 2: Batch create posts
mutation {
  createPosts(input: { posts: [
    { profileId: "prof_ig_123"
      text: "Monday motivation 🌱 #smallbusiness"
      scheduledAt: "2025-04-07T09:00:00Z"
      tagIds: ["tag_motivation"] }
    { profileId: "prof_ig_123"
      text: "Behind the scenes ✨ #bts"
      scheduledAt: "2025-04-09T09:00:00Z" }
  ]}) { success results { success post { id } error } }
}

# Step 3: Verify queue
query {
  posts(status: QUEUED, scheduledAfter: "2025-04-07"
        scheduledBefore: "2025-04-13"
        sortBy: SCHEDULED_AT_ASC) {
    edges { node { text scheduledAt profile { channel } } }
    totalCount
  }
}`,
        lang: "graphql",
      },
      {
        heading: "Analytics Dashboard",
        body: "Pull profile-level metrics and top-performing posts. Compare engagement rates across channels to see where your audience is most active.",
        code: `# Profile-level metrics
query {
  profiles {
    channel username
    analytics(period: WEEK) {
      followers followersChange
      impressions totalEngagement engagementRate
    }
  }
}

# Top posts by engagement
query {
  posts(status: SENT, sortBy: ENGAGEMENT_DESC, limit: 5) {
    edges { node {
      text
      profile { channel }
      analytics { impressions likes comments shares clicks }
    }}
  }
}`,
        lang: "graphql",
      },
      {
        heading: "RSS-to-Buffer Pipeline",
        body: "Monitor a blog feed, generate platform-appropriate text, create drafts via the API. A human reviews and approves in Buffer's UI. Omit scheduledAt to keep posts as drafts.",
        code: `mutation {
  createPosts(input: { posts: [
    { profileId: "prof_x_456"
      text: "New on the blog: Content Calendar Guide → myblog.com/cal" }
    { profileId: "prof_li_789"
      text: "Just published a guide on content calendars for small businesses.\\n\\nCovers the 3 biggest mistakes and how to avoid them.\\n\\nRead: myblog.com/cal" }
  ]}) {
    success
    results { success post { id status } error }
  }
}
# Both created as DRAFT (no scheduledAt)`,
        lang: "graphql",
      },
    ],
  },
  design: {
    title: "Schema Annotation Strategy",
    subtitle: "How to write schema descriptions that work for developers, docs, IDEs, and AI agents simultaneously",
    sections: [
      {
        heading: "The Opportunity",
        body: "Your GraphQL schema is already the single source of truth for your API's structure. With the right annotation strategy, it also becomes the source of truth for documentation, IDE hints, and AI agent integration. One investment serves every consumer.",
      },
      {
        heading: "Descriptions Are Metadata, Not Narrative",
        body: "Schema descriptions might look like prose, but they function as structured metadata. Each description is bound to a specific field, argument, or enum value by the schema itself. An AI agent doesn't need to parse a paragraph and guess which field it applies to. The schema defines that relationship explicitly. This is the difference between writing a Markdown doc that says 'the scheduledAt field accepts an ISO 8601 datetime' and attaching that same information directly to the scheduledAt field definition. Both contain the same words, but the schema version is unambiguous because the structure does the work.",
      },
      {
        heading: "Writing Descriptions for Dual Audiences",
        body: "Every description should be a complete sentence that makes sense without surrounding context. A developer skimming the docs and an AI agent parsing the schema need the same information: what this field does, what format it expects, and what happens when you use it. If a description requires you to read another page to understand it, it's not doing enough work.",
        code: `# Weak: requires context from elsewhere
"""Scheduling time."""
scheduledAt: DateTime

# Strong: self-contained, documents behavior
"""
When to publish. ISO 8601 datetime.
If provided, the post is created as QUEUED.
If omitted, the post is created as DRAFT.
Must be in the future.
"""
scheduledAt: DateTime`,
        lang: "graphql",
      },
      {
        heading: "Embed Constraints Where They're Used",
        body: "Don't make developers (or agents) look up constraints in a separate table. Platform character limits belong in the Channel enum descriptions. Required formats belong on the argument. Preconditions belong on the mutation. When an AI agent reads the Channel enum and sees 'X (formerly Twitter) — text posts up to 280 characters,' it generates correctly sized content without a separate lookup.",
        code: `# Weak: just a label
X

# Strong: constraint is discoverable in context
"""X (formerly Twitter) — text posts up to 280 characters"""
X`,
        lang: "graphql",
      },
      {
        heading: "Document Side Effects on Mutations",
        body: "Mutations aren't just data changes. They have behavioral consequences. Document what state transitions happen, what preconditions must be met, and what errors to expect. This is where most API docs fall short, and where the biggest gains are for both human developers and AI agents.",
        code: `# Documents the precondition AND the consequence
"""
Revert a queued post back to draft status.
The post must currently be QUEUED.
Returns an error if the post is already SENT or DRAFT.
"""
unqueuePost(id: ID!): UnqueuePostPayload!`,
        lang: "graphql",
      },
      {
        heading: "The Thin Bridge Pattern",
        body: "When schema descriptions carry enough context, the tooling layer stays thin. An MCP server can read the schema via introspection and expose every operation as a tool with no manual mapping. If an AI agent struggles with a tool, that's a signal the schema description needs improvement, not the bridge. Fix the source of truth and every consumer benefits.",
      },
      {
        heading: "See It in Action",
        body: "The AI Preview page demonstrates this approach. Claude was given only the annotated schema as context — no custom instructions, no few-shot examples, no tool definitions. The descriptions alone were sufficient for the model to select correct operations and structure valid queries.",
      },
    ],
  },
};

// ─── MCP TOOLS ───────────────────────────────────────────────────────────────
const MCP_TOOLS = [
  { name: "query_profile", desc: "Get a single profile by ID", type: "read" },
  { name: "query_profiles", desc: "List all connected profiles", type: "read" },
  { name: "query_post", desc: "Get a single post by ID", type: "read" },
  { name: "query_posts", desc: "List posts with filters", type: "read" },
  { name: "query_tags", desc: "List all tags", type: "read" },
  { name: "query_webhooks", desc: "List webhook subscriptions", type: "read" },
  { name: "query_comments", desc: "Get comments on a post", type: "read" },
  { name: "query_rateLimit", desc: "Check rate limit budget", type: "read" },
  { name: "mutation_createPost", desc: "Create a post for one profile", type: "write" },
  { name: "mutation_createPosts", desc: "Batch create across profiles", type: "write" },
  { name: "mutation_updatePost", desc: "Edit a draft or queued post", type: "write" },
  { name: "mutation_deletePost", desc: "Permanently delete a post", type: "write" },
  { name: "mutation_unqueuePost", desc: "Revert queued post to draft", type: "write" },
  { name: "mutation_publishNow", desc: "Publish immediately", type: "write" },
  { name: "mutation_addToQueue", desc: "Add draft to queue", type: "write" },
  { name: "mutation_updateSchedule", desc: "Set auto-publish schedule", type: "write" },
  { name: "mutation_createTag", desc: "Create a new tag", type: "write" },
  { name: "mutation_tagPost", desc: "Tag a post", type: "write" },
  { name: "mutation_untagPost", desc: "Remove tag from post", type: "write" },
  { name: "mutation_uploadMedia", desc: "Upload image or video", type: "write" },
  { name: "mutation_createWebhook", desc: "Register a webhook", type: "write" },
  { name: "mutation_deleteWebhook", desc: "Remove a webhook", type: "write" },
  { name: "mutation_replyToComment", desc: "Reply to a comment", type: "write" },
];

// ─── STYLES ──────────────────────────────────────────────────────────────────
const colors = {
  bg: "#f4f5f7",
  surface: "#ffffff",
  surfaceHover: "#eef0f3",
  border: "#d8dce3",
  borderAccent: "#c4c9d4",
  text: "#1a1f2e",
  textMuted: "#4a5168",
  textDim: "#8890a4",
  accent: "#2563eb",
  accentSoft: "#2563eb14",
  green: "#16a34a",
  greenSoft: "#16a34a14",
  amber: "#ca8a04",
  amberSoft: "#ca8a0414",
  red: "#dc2626",
  redSoft: "#dc262614",
  cyan: "#0284c7",
  cyanSoft: "#0284c714",
};

// ─── COMPONENTS ──────────────────────────────────────────────────────────────

function CodeBlock({ code, lang }) {
  const [copied, setCopied] = useState(false);
  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <div style={{ position: "relative", marginTop: 12, marginBottom: 16 }}>
      <div style={{
        background: "#1e2130",
        border: `1px solid ${colors.border}`,
        borderRadius: 8,
      }}>
        <div style={{
          display: "flex", justifyContent: "space-between", alignItems: "center",
          padding: "6px 12px", background: "#252a3a", borderBottom: `1px solid ${colors.border}`,
        }}>
          <span style={{ fontSize: 11, color: "#6b7280", fontFamily: "monospace", textTransform: "uppercase", letterSpacing: 1 }}>{lang}</span>
          <button onClick={handleCopy} style={{
            background: "none", border: "none", color: "#8890a4", cursor: "pointer", fontSize: 11,
            padding: "2px 8px", borderRadius: 4, transition: "color 0.2s",
          }}>
            {copied ? "✓ Copied" : "Copy"}
          </button>
        </div>
        <pre style={{
          padding: 16, margin: 0, overflow: "auto", fontSize: 13, lineHeight: 1.6,
          color: "#c4cbd8", fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
          maxHeight: 400,
        }}>
          <code>{code}</code>
        </pre>
      </div>
    </div>
  );
}

function NavItem({ label, active, onClick, icon }) {
  return (
    <button onClick={onClick} style={{
      display: "flex", alignItems: "center", gap: 8,
      padding: "8px 14px", borderRadius: 6, border: "none", cursor: "pointer",
      background: active ? colors.accentSoft : "transparent",
      color: active ? colors.accent : colors.textMuted,
      fontSize: 13, fontWeight: active ? 600 : 400, fontFamily: "inherit",
      transition: "all 0.2s", width: "100%", textAlign: "left",
    }}>
      <span style={{ fontSize: 15 }}>{icon}</span>
      {label}
    </button>
  );
}

function Badge({ children, color = colors.accent, bg = colors.accentSoft }) {
  return (
    <span style={{
      display: "inline-block", padding: "2px 8px", borderRadius: 4,
      fontSize: 11, fontWeight: 600, color, background: bg,
      fontFamily: "monospace", letterSpacing: 0.5,
    }}>
      {children}
    </span>
  );
}

// ─── PAGES ───────────────────────────────────────────────────────────────────

function LandingPage({ onNavigate }) {
  return (
    <div style={{ maxWidth: 800, margin: "0 auto", padding: "60px 20px" }}>
      <div style={{ marginBottom: 48 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 16 }}>
          <div style={{
            width: 36, height: 36, borderRadius: 8, background: colors.accent,
            display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, fontWeight: 700, color: "#fff",
          }}>B</div>
          <span style={{ fontSize: 13, color: colors.textDim, fontFamily: "monospace", letterSpacing: 1, textTransform: "uppercase" }}>
            Developer Experience Kit
          </span>
        </div>
        <h1 style={{
          fontSize: 40, fontWeight: 700, lineHeight: 1.15, color: colors.text, margin: "0 0 20px",
          fontFamily: "'DM Serif Display', Georgia, serif",
        }}>
          What Buffer's new API<br />developer experience<br />could look like.
        </h1>
        <p style={{ fontSize: 17, lineHeight: 1.7, color: colors.textMuted, maxWidth: 600, margin: "0 0 32px" }}>
          A proof of concept exploring how to build developer documentation that works for
          humans reading docs, AI agents parsing schemas, and everyone in between. Inspired
          by Buffer's API rebuild and designed to show what modern developer experience could look like.
        </p>
        <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
          <button onClick={() => onNavigate("ai")} style={{
            padding: "12px 24px", borderRadius: 8, border: "none", cursor: "pointer",
            background: colors.accent, color: "#fff", fontSize: 14, fontWeight: 600, fontFamily: "inherit",
          }}>
            AI Preview →
          </button>
          <button onClick={() => onNavigate("reference")} style={{
            padding: "12px 24px", borderRadius: 8, border: `1px solid ${colors.border}`, cursor: "pointer",
            background: "transparent", color: colors.text, fontSize: 14, fontWeight: 500, fontFamily: "inherit",
          }}>
            Read the Docs
          </button>
        </div>
      </div>

      <div style={{
        border: `1px solid ${colors.border}`, borderRadius: 12, padding: 32,
        background: colors.surface, marginBottom: 48,
      }}>
        <h2 style={{ fontSize: 18, fontWeight: 600, color: colors.text, margin: "0 0 8px" }}>What's in the kit</h2>
        <p style={{ fontSize: 14, color: colors.textMuted, margin: "0 0 24px" }}>
          Everything a Developer Advocate would build for an API launch.
        </p>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
          {[
            { icon: "📐", title: "Annotated GraphQL Schema", desc: "1,100+ lines with descriptions designed for both human and AI consumption", link: "reference" },
            { icon: "🚀", title: "Quickstart Guide", desc: "JavaScript, Python, and curl examples. Zero to first call in 5 minutes.", link: "quickstart" },
            { icon: "⚠️", title: "Error Reference", desc: "Every error with response bodies, explanations, and fixes. Not just a code table.", link: "errors" },
            { icon: "🔄", title: "Workflow Patterns", desc: "Content calendars, analytics dashboards, RSS pipelines, cross-channel publishing.", link: "workflows" },
            { icon: "🤖", title: "Annotation Strategy", desc: "How to write schema descriptions that serve developers, docs, and AI agents from one source.", link: "design" },
            { icon: "🔌", title: "Thin-Bridge MCP Server", desc: "~250 lines. Schema introspection → MCP tools. No manual mapping.", link: "mcp" },
          ].map((item, i) => (
            <div key={i} onClick={() => onNavigate(item.link)} style={{
              padding: 16, borderRadius: 8, border: `1px solid ${colors.border}`,
              cursor: "pointer", transition: "all 0.2s",
            }}
            onMouseEnter={e => { e.currentTarget.style.borderColor = colors.accent; e.currentTarget.style.background = colors.surfaceHover; }}
            onMouseLeave={e => { e.currentTarget.style.borderColor = colors.border; e.currentTarget.style.background = "transparent"; }}
            >
              <div style={{ fontSize: 20, marginBottom: 8 }}>{item.icon}</div>
              <h3 style={{ fontSize: 14, fontWeight: 600, color: colors.text, margin: "0 0 6px" }}>{item.title}</h3>
              <p style={{ fontSize: 12, color: colors.textMuted, margin: 0, lineHeight: 1.5 }}>{item.desc}</p>
            </div>
          ))}
        </div>
      </div>

      <div style={{ textAlign: "center", padding: "20px 0", borderTop: `1px solid ${colors.border}` }}>
        <p style={{ fontSize: 13, color: colors.textDim, margin: 0 }}>
          Built by <a href="https://grzeti.ch" style={{ color: colors.accent, textDecoration: "none" }}>Ed Grzetich</a> as a proof of concept
          for the <a href="https://buffer.com/developer-api" style={{ color: colors.accent, textDecoration: "none" }}>Buffer Developer API</a> rebuild.
        </p>
      </div>
    </div>
  );
}

function DocsPage({ docKey }) {
  const doc = DOCS[docKey];
  if (!doc) return null;
  return (
    <div style={{ maxWidth: 760, margin: "0 auto", padding: "40px 20px" }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, color: colors.text, margin: "0 0 8px", fontFamily: "'DM Serif Display', Georgia, serif" }}>
        {doc.title}
      </h1>
      <p style={{ fontSize: 15, color: colors.textMuted, margin: "0 0 40px" }}>{doc.subtitle}</p>
      {doc.sections.map((section, i) => (
        <div key={i} style={{ marginBottom: section.heading ? 40 : 16 }}>
          {section.heading && (
            <h2 style={{ fontSize: 20, fontWeight: 600, color: colors.text, margin: "0 0 10px" }}>
              {section.heading}
            </h2>
          )}
          {section.body && (
            <p style={{ fontSize: 14, color: colors.textMuted, lineHeight: 1.7, margin: "0 0 4px" }}>
              {section.body}
            </p>
          )}
          {section.code && <CodeBlock code={section.code} lang={section.lang || "graphql"} />}
        </div>
      ))}
    </div>
  );
}

// ─── SCHEMA REFERENCE DATA ──────────────────────────────────────────────────
// One example per category to demonstrate documentation depth without
// prescribing Buffer's full API surface.

function APIReferencePage() {
  const [section, setSection] = useState("reads");

  const paramTableStyle = {
    width: "100%", borderCollapse: "collapse", fontSize: 13, marginTop: 12,
  };
  const thStyle = {
    textAlign: "left", padding: "8px 12px", fontSize: 11, fontWeight: 600,
    color: colors.textDim, textTransform: "uppercase", letterSpacing: 1,
    borderBottom: `1px solid ${colors.border}`,
  };
  const tdStyle = {
    padding: "8px 12px", borderBottom: `1px solid ${colors.border}`,
    color: colors.textMuted, verticalAlign: "top",
  };
  const codeStyle = { fontFamily: "'JetBrains Mono', 'Fira Code', monospace", fontSize: 12 };

  return (
    <div style={{ maxWidth: 760, margin: "0 auto", padding: "40px 20px" }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, color: colors.text, margin: "0 0 8px", fontFamily: "'DM Serif Display', Georgia, serif" }}>
        API Reference
      </h1>
      <p style={{ fontSize: 15, color: colors.textMuted, margin: "0 0 8px" }}>
        Example reference entries showing the level of detail each operation, type, and enum would receive.
      </p>
      <p style={{ fontSize: 13, color: colors.textDim, margin: "0 0 24px" }}>
        One example per category. A production reference would follow this format for every operation in the schema.
      </p>
      <div style={{ display: "flex", gap: 8, marginBottom: 24 }}>
        {[
          { key: "reads", label: "Read Operations" },
          { key: "writes", label: "Write Operations" },
          { key: "types", label: "Types" },
          { key: "enums", label: "Enums" },
        ].map(t => (
          <button key={t.key} onClick={() => setSection(t.key)} style={{
            padding: "6px 16px", borderRadius: 6, border: `1px solid ${section === t.key ? colors.accent : colors.border}`,
            background: section === t.key ? colors.accentSoft : "transparent",
            color: section === t.key ? colors.accent : colors.textMuted,
            cursor: "pointer", fontSize: 13, fontFamily: "inherit", fontWeight: 500,
          }}>
            {t.label}
          </button>
        ))}
      </div>

      {section === "reads" && (
        <div style={{ padding: 24, borderRadius: 12, border: `1px solid ${colors.border}`, background: colors.surface }}>
          <code style={{ fontSize: 16, color: colors.accent, fontWeight: 600 }}>posts</code>
          <code style={{ fontSize: 12, color: colors.cyan, marginLeft: 12 }}>→ PostConnection!</code>
          <p style={{ fontSize: 14, color: colors.textMuted, lineHeight: 1.7, margin: "12px 0 0" }}>
            Search and filter posts across all connected profiles. Returns a paginated connection with edges, 
            nodes, and page info. Supports filtering by profile, status, tag, and date range, with configurable sort order.
          </p>
          <table style={paramTableStyle}>
            <thead>
              <tr>
                <th style={thStyle}>Parameter</th>
                <th style={thStyle}>Type</th>
                <th style={thStyle}>Required</th>
                <th style={thStyle}>Description</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>profileId</td>
                <td style={{ ...tdStyle, ...codeStyle }}>ID</td>
                <td style={tdStyle}>No</td>
                <td style={tdStyle}>Filter to a single profile. Omit to search across all profiles.</td>
              </tr>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>status</td>
                <td style={{ ...tdStyle, ...codeStyle }}>PostStatus</td>
                <td style={tdStyle}>No</td>
                <td style={tdStyle}>Filter by status: DRAFT, QUEUED, SENT, or FAILED.</td>
              </tr>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>tagId</td>
                <td style={{ ...tdStyle, ...codeStyle }}>ID</td>
                <td style={tdStyle}>No</td>
                <td style={tdStyle}>Filter to posts with a specific tag.</td>
              </tr>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>scheduledAfter</td>
                <td style={{ ...tdStyle, ...codeStyle }}>DateTime</td>
                <td style={tdStyle}>No</td>
                <td style={tdStyle}>Only return posts scheduled after this ISO 8601 datetime.</td>
              </tr>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>sortBy</td>
                <td style={{ ...tdStyle, ...codeStyle }}>PostSortOrder</td>
                <td style={tdStyle}>No</td>
                <td style={tdStyle}>Sort order. Default: SCHEDULED_AT_DESC.</td>
              </tr>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>limit</td>
                <td style={{ ...tdStyle, ...codeStyle }}>Int</td>
                <td style={tdStyle}>No</td>
                <td style={tdStyle}>Max results to return. Default: 20, max: 100.</td>
              </tr>
            </tbody>
          </table>
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>Schema</h4>
          <CodeBlock code={`"""
Search and filter posts across all connected profiles.
Returns a paginated connection. Supports filtering by
profile, status, tag, and date range.
"""
posts(
  profileId: ID
  status: PostStatus
  tagId: ID
  scheduledAfter: DateTime
  sortBy: PostSortOrder = SCHEDULED_AT_DESC
  limit: Int = 20
): PostConnection!`} lang="graphql" />
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>JavaScript</h4>
          <CodeBlock code={`const response = await fetch("https://api.buffer.com/graphql", {
  method: "POST",
  headers: {
    "Authorization": "Bearer YOUR_ACCESS_TOKEN",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query: \`{
      posts(status: SENT, sortBy: ENGAGEMENT_DESC, limit: 5) {
        edges {
          node { id text sentAt analytics { impressions likes } }
        }
      }
    }\`,
  }),
});

const { data } = await response.json();
data.posts.edges.forEach(e => console.log(e.node));`} lang="javascript" />
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>Python</h4>
          <CodeBlock code={`response = requests.post(
    "https://api.buffer.com/graphql",
    headers={
        "Authorization": "Bearer YOUR_ACCESS_TOKEN",
        "Content-Type": "application/json",
    },
    json={
        "query": """{
            posts(status: SENT, sortBy: ENGAGEMENT_DESC, limit: 5) {
                edges {
                    node { id text sentAt analytics { impressions likes } }
                }
            }
        }"""
    },
)

for edge in response.json()["data"]["posts"]["edges"]:
    print(edge["node"])`} lang="python" />
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>curl</h4>
          <CodeBlock code={`curl -X POST https://api.buffer.com/graphql \\
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"query": "{ posts(status: SENT, sortBy: ENGAGEMENT_DESC, limit: 5) { edges { node { id text sentAt } } } }"}'`} lang="curl" />
        </div>
      )}
        <div style={{ padding: 24, borderRadius: 12, border: `1px solid ${colors.border}`, background: colors.surface }}>
          <code style={{ fontSize: 16, color: colors.amber, fontWeight: 600 }}>createPost</code>
          <code style={{ fontSize: 12, color: colors.cyan, marginLeft: 12 }}>→ CreatePostPayload!</code>
          <p style={{ fontSize: 14, color: colors.textMuted, lineHeight: 1.7, margin: "12px 0 0" }}>
            Create a post for a single profile. If <code style={codeStyle}>scheduledAt</code> is provided, the post 
            is created as QUEUED and will publish at the specified time. If omitted, the post is created as DRAFT. 
            Always check both <code style={codeStyle}>success</code> and <code style={codeStyle}>error</code> in the response.
          </p>
          <table style={paramTableStyle}>
            <thead>
              <tr>
                <th style={thStyle}>Field</th>
                <th style={thStyle}>Type</th>
                <th style={thStyle}>Required</th>
                <th style={thStyle}>Description</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>profileId</td>
                <td style={{ ...tdStyle, ...codeStyle }}>ID!</td>
                <td style={tdStyle}>Yes</td>
                <td style={tdStyle}>The profile to create the post on.</td>
              </tr>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>text</td>
                <td style={{ ...tdStyle, ...codeStyle }}>String!</td>
                <td style={tdStyle}>Yes</td>
                <td style={tdStyle}>Post content. Must respect the channel's character limit (see Channel enum).</td>
              </tr>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>scheduledAt</td>
                <td style={{ ...tdStyle, ...codeStyle }}>DateTime</td>
                <td style={tdStyle}>No</td>
                <td style={tdStyle}>ISO 8601 datetime. If provided → QUEUED. If omitted → DRAFT. Must be in the future.</td>
              </tr>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>mediaIds</td>
                <td style={{ ...tdStyle, ...codeStyle }}>[ID!]</td>
                <td style={tdStyle}>No</td>
                <td style={tdStyle}>IDs from uploadMedia. Attach images or video to the post.</td>
              </tr>
              <tr>
                <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>tagIds</td>
                <td style={{ ...tdStyle, ...codeStyle }}>[ID!]</td>
                <td style={tdStyle}>No</td>
                <td style={tdStyle}>Tags to apply to the post at creation time.</td>
              </tr>
            </tbody>
          </table>
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>Schema</h4>
          <CodeBlock code={`"""
Create a post for a single profile.
If scheduledAt is provided, the post is created as QUEUED.
If omitted, the post is created as DRAFT.
Always check success and error in the response.
"""
createPost(input: CreatePostInput!): CreatePostPayload!

input CreatePostInput {
  profileId: ID!
  text: String!
  scheduledAt: DateTime
  mediaIds: [ID!]
  tagIds: [ID!]
}`} lang="graphql" />
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>JavaScript</h4>
          <CodeBlock code={`const response = await fetch("https://api.buffer.com/graphql", {
  method: "POST",
  headers: {
    "Authorization": "Bearer YOUR_ACCESS_TOKEN",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query: \`mutation($input: CreatePostInput!) {
      createPost(input: $input) {
        success
        post { id status scheduledAt }
        error
      }
    }\`,
    variables: {
      input: {
        profileId: "prof_abc123",
        text: "Excited to share what we've been working on! 🚀",
        scheduledAt: "2025-04-01T14:30:00Z",
      },
    },
  }),
});

const { data } = await response.json();
console.log(data.createPost.post);`} lang="javascript" />
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>Python</h4>
          <CodeBlock code={`response = requests.post(
    "https://api.buffer.com/graphql",
    headers={
        "Authorization": "Bearer YOUR_ACCESS_TOKEN",
        "Content-Type": "application/json",
    },
    json={
        "query": """mutation($input: CreatePostInput!) {
            createPost(input: $input) {
                success
                post { id status scheduledAt }
                error
            }
        }""",
        "variables": {
            "input": {
                "profileId": "prof_abc123",
                "text": "Excited to share what we've been working on! 🚀",
                "scheduledAt": "2025-04-01T14:30:00Z"
            }
        }
    },
)

print(response.json()["data"]["createPost"])`} lang="python" />
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>curl</h4>
          <CodeBlock code={`curl -X POST https://api.buffer.com/graphql \\
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{
    "query": "mutation($input: CreatePostInput!) { createPost(input: $input) { success post { id status scheduledAt } error } }",
    "variables": {
      "input": {
        "profileId": "prof_abc123",
        "text": "Excited to share what we've been working on! 🚀",
        "scheduledAt": "2025-04-01T14:30:00Z"
      }
    }
  }'`} lang="curl" />
        </div>
      )}

      {section === "types" && (
        <div style={{ padding: 24, borderRadius: 12, border: `1px solid ${colors.border}`, background: colors.surface }}>
          <code style={{ fontSize: 16, color: colors.text, fontWeight: 600 }}>Post</code>
          <p style={{ fontSize: 14, color: colors.textMuted, lineHeight: 1.7, margin: "12px 0 0" }}>
            A single piece of content for one social media profile. A Post moves through a lifecycle: 
            DRAFT → QUEUED → SENT (or FAILED). Drafts can be edited, queued posts can be unqueued 
            back to draft, and sent posts are read-only.
          </p>
          <table style={paramTableStyle}>
            <thead>
              <tr>
                <th style={thStyle}>Field</th>
                <th style={thStyle}>Type</th>
                <th style={thStyle}>Description</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["id", "ID!", "Unique identifier"],
                ["text", "String!", "Post content as submitted"],
                ["status", "PostStatus!", "Current lifecycle state: DRAFT, QUEUED, SENT, or FAILED"],
                ["profile", "Profile!", "The social media profile this post belongs to"],
                ["media", "[Media!]", "Attached images or video, if any"],
                ["scheduledAt", "DateTime", "When the post is scheduled to publish (null for drafts)"],
                ["sentAt", "DateTime", "When the post was actually published (null until sent)"],
                ["createdAt", "DateTime!", "When the post was created"],
                ["updatedAt", "DateTime!", "When the post was last modified"],
                ["tags", "[Tag!]!", "Tags applied to this post for organization"],
                ["error", "String", "Error message if the post failed to publish"],
                ["analytics", "PostAnalytics", "Engagement metrics (only available for SENT posts)"],
              ].map(([field, type, desc], i) => (
                <tr key={i}>
                  <td style={{ ...tdStyle, ...codeStyle, color: colors.text }}>{field}</td>
                  <td style={{ ...tdStyle, ...codeStyle }}>{type}</td>
                  <td style={tdStyle}>{desc}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>Schema</h4>
          <CodeBlock code={`"""
A single piece of content for one social media profile.
Lifecycle: DRAFT → QUEUED → SENT (or FAILED).
Drafts can be edited. Queued posts can be unqueued.
Sent posts are read-only.
"""
type Post {
  id: ID!
  text: String!
  status: PostStatus!
  profile: Profile!
  media: [Media!]
  scheduledAt: DateTime
  sentAt: DateTime
  createdAt: DateTime!
  updatedAt: DateTime!
  tags: [Tag!]!
  error: String
  analytics: PostAnalytics
}`} lang="graphql" />
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>JavaScript</h4>
          <CodeBlock code={`const response = await fetch("https://api.buffer.com/graphql", {
  method: "POST",
  headers: {
    "Authorization": "Bearer YOUR_ACCESS_TOKEN",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query: \`{
      post(id: "post_abc123") {
        id text status
        profile { name channel }
        scheduledAt sentAt
        tags { name }
        analytics { impressions likes comments shares }
      }
    }\`,
  }),
});

const { data } = await response.json();
console.log(data.post);`} lang="javascript" />
        </div>
      )}

      {section === "enums" && (
        <div style={{ padding: 24, borderRadius: 12, border: `1px solid ${colors.border}`, background: colors.surface }}>
          <code style={{ fontSize: 16, color: colors.text, fontWeight: 600 }}>Channel</code>
          <p style={{ fontSize: 14, color: colors.textMuted, lineHeight: 1.7, margin: "12px 0 0" }}>
            Supported social media platforms. Each value includes the platform name and character limit 
            in its schema description, so AI agents and developers can validate content length without a separate lookup.
          </p>
          <table style={paramTableStyle}>
            <thead>
              <tr>
                <th style={thStyle}>Value</th>
                <th style={thStyle}>Description</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["INSTAGRAM", "Instagram — caption up to 2,200 characters"],
                ["FACEBOOK", "Facebook — text posts up to 63,206 characters"],
                ["LINKEDIN", "LinkedIn — text posts up to 3,000 characters"],
                ["X", "X (formerly Twitter) — text posts up to 280 characters"],
                ["BLUESKY", "Bluesky — text posts up to 300 characters"],
                ["THREADS", "Threads — text posts up to 500 characters"],
                ["TIKTOK", "TikTok — video caption up to 2,200 characters"],
                ["PINTEREST", "Pinterest — pin description up to 500 characters"],
                ["YOUTUBE", "YouTube — video description up to 5,000 characters"],
                ["MASTODON", "Mastodon — text posts up to 500 characters (default)"],
              ].map(([value, desc], i) => (
                <tr key={i}>
                  <td style={{ ...tdStyle, ...codeStyle, color: colors.accent }}>{value}</td>
                  <td style={tdStyle}>{desc}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>Schema</h4>
          <CodeBlock code={`"""Supported social media platforms."""
enum Channel {
  """Instagram — caption up to 2,200 characters"""
  INSTAGRAM
  """Facebook — text posts up to 63,206 characters"""
  FACEBOOK
  """LinkedIn — text posts up to 3,000 characters"""
  LINKEDIN
  """X (formerly Twitter) — text posts up to 280 characters"""
  X
  """Bluesky — text posts up to 300 characters"""
  BLUESKY
  """Threads — text posts up to 500 characters"""
  THREADS
  """TikTok — video caption up to 2,200 characters"""
  TIKTOK
  """Pinterest — pin description up to 500 characters"""
  PINTEREST
  """YouTube — video description up to 5,000 characters"""
  YOUTUBE
  """Mastodon — text posts up to 500 characters (default)"""
  MASTODON
}`} lang="graphql" />
          <h4 style={{ fontSize: 13, fontWeight: 600, color: colors.textDim, margin: "24px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>JavaScript</h4>
          <CodeBlock code={`// Filter profiles by channel
const response = await fetch("https://api.buffer.com/graphql", {
  method: "POST",
  headers: {
    "Authorization": "Bearer YOUR_ACCESS_TOKEN",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query: \`{
      profiles(channel: INSTAGRAM) {
        id name username isConnected
      }
    }\`,
  }),
});

const { data } = await response.json();
console.log(data.profiles);`} lang="javascript" />
        </div>
      )}
    </div>
  );
}

function MCPServerPage() {
  const reads = MCP_TOOLS.filter(t => t.type === "read");
  const writes = MCP_TOOLS.filter(t => t.type === "write");
  return (
    <div style={{ maxWidth: 760, margin: "0 auto", padding: "40px 20px" }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, color: colors.text, margin: "0 0 8px", fontFamily: "'DM Serif Display', Georgia, serif" }}>
        MCP Server
      </h1>
      <p style={{ fontSize: 15, color: colors.textMuted, margin: "0 0 8px" }}>
        A well-annotated GraphQL schema can be rapidly integrated into an MCP server, giving AI agents direct access to the API without manual tool definitions.
      </p>
      <p style={{ fontSize: 13, color: colors.textDim, margin: "0 0 32px" }}>
        {MCP_TOOLS.length} tools generated from the schema via introspection. ~250 lines of glue code.
        The server reads the schema, turns each query into a read tool and each mutation into a write tool. 
        Names, descriptions, and parameters come directly from the type definitions. When the schema evolves, tools update automatically.
      </p>

      <h3 style={{ fontSize: 13, color: colors.green, fontWeight: 600, margin: "0 0 12px", textTransform: "uppercase", letterSpacing: 1 }}>
        Read ({reads.length})
      </h3>
      <div style={{ display: "flex", flexDirection: "column", gap: 4, marginBottom: 24 }}>
        {reads.map(t => (
          <div key={t.name} style={{
            display: "flex", justifyContent: "space-between", alignItems: "center",
            padding: "10px 14px", borderRadius: 6, border: `1px solid ${colors.border}`,
            background: colors.surface,
          }}>
            <code style={{ fontSize: 13, color: colors.cyan }}>{t.name}</code>
            <span style={{ fontSize: 12, color: colors.textMuted }}>{t.desc}</span>
          </div>
        ))}
      </div>
      <h3 style={{ fontSize: 13, color: colors.amber, fontWeight: 600, margin: "0 0 12px", textTransform: "uppercase", letterSpacing: 1 }}>
        Write ({writes.length})
      </h3>
      <div style={{ display: "flex", flexDirection: "column", gap: 4, marginBottom: 32 }}>
        {writes.map(t => (
          <div key={t.name} style={{
            display: "flex", justifyContent: "space-between", alignItems: "center",
            padding: "10px 14px", borderRadius: 6, border: `1px solid ${colors.border}`,
            background: colors.surface,
          }}>
            <code style={{ fontSize: 13, color: colors.amber }}>{t.name}</code>
            <span style={{ fontSize: 12, color: colors.textMuted }}>{t.desc}</span>
          </div>
        ))}
      </div>

      <div style={{
        border: `1px solid ${colors.border}`, borderRadius: 12, padding: 24,
        background: colors.surface,
      }}>
        <h3 style={{ fontSize: 15, fontWeight: 600, color: colors.text, margin: "0 0 10px" }}>
          The thin bridge pattern
        </h3>
        <div style={{ fontSize: 13, color: colors.textMuted, lineHeight: 1.7 }}>
          <p style={{ margin: "0 0 10px" }}>
            The MCP server is intentionally minimal. It reads the schema via introspection and exposes each 
            operation as a tool. No hand-written descriptions, no manual parameter mapping, no domain logic in the bridge.
          </p>
          <p style={{ margin: 0 }}>
            When an AI agent struggles with a tool, that's a signal the <strong style={{ color: colors.text }}>schema description</strong> needs 
            improvement, not the bridge. Fix the source of truth and every consumer benefits: docs, IDEs, MCP tools, and direct API callers.
          </p>
        </div>
      </div>
    </div>
  );
}

function AIPage() {
  const [selectedIdx, setSelectedIdx] = useState(null);
  const [displayedOutput, setDisplayedOutput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const resultRef = useRef(null);
  const intervalRef = useRef(null);

  const startReplay = useCallback((idx) => {
    if (intervalRef.current) clearInterval(intervalRef.current);
    setSelectedIdx(idx);
    setDisplayedOutput("");
    setIsTyping(true);
    const fullOutput = DEMO_PAIRS[idx].output;
    let charIdx = 0;
    intervalRef.current = setInterval(() => {
      charIdx += 3;
      if (charIdx >= fullOutput.length) {
        clearInterval(intervalRef.current);
        setDisplayedOutput(fullOutput);
        setIsTyping(false);
      } else {
        setDisplayedOutput(fullOutput.substring(0, charIdx));
      }
    }, 8);
  }, []);

  useEffect(() => {
    return () => { if (intervalRef.current) clearInterval(intervalRef.current); };
  }, []);

  useEffect(() => {
    if (displayedOutput && resultRef.current) {
      resultRef.current.scrollIntoView({ behavior: "smooth", block: "nearest" });
    }
  }, [selectedIdx]);

  return (
    <div style={{ maxWidth: 760, margin: "0 auto", padding: "40px 20px" }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, color: colors.text, margin: "0 0 8px", fontFamily: "'DM Serif Display', Georgia, serif" }}>
        AI Preview
      </h1>
      <p style={{ fontSize: 15, color: colors.textMuted, margin: "0 0 8px" }}>
        Pre-recorded responses showing how Claude identifies the correct API operations from natural language prompts, 
        using only the GraphQL schema as context. No custom instructions, no few-shot examples, no tool definitions.
      </p>
      <p style={{ fontSize: 13, color: colors.textDim, margin: "0 0 32px" }}>
        This is a simulated preview, not a live API call. The purpose is to demonstrate that well-annotated schema 
        descriptions are sufficient for a model to select the right operations and structure valid queries. 
        Variable values and placeholder IDs are illustrative.
      </p>

      <div style={{ display: "flex", flexDirection: "column", gap: 6, marginBottom: 32 }}>
        {DEMO_PAIRS.map((pair, i) => (
          <button key={i} onClick={() => startReplay(i)} style={{
            padding: "12px 16px", borderRadius: 8, border: `1px solid ${selectedIdx === i ? colors.accent : colors.border}`,
            background: selectedIdx === i ? colors.accentSoft : colors.surface,
            color: selectedIdx === i ? colors.text : colors.textMuted,
            fontSize: 13, cursor: "pointer", fontFamily: "inherit", textAlign: "left",
            transition: "all 0.2s", lineHeight: 1.5,
          }}>
            <span style={{ color: colors.textDim, marginRight: 8, fontFamily: "monospace" }}>→</span>
            {pair.prompt}
          </button>
        ))}
      </div>

      {selectedIdx !== null && (
        <div ref={resultRef}>
          <div style={{
            padding: "12px 16px", borderRadius: "8px 8px 0 0", border: `1px solid ${colors.border}`,
            borderBottom: "none", background: "#252a3a",
            display: "flex", alignItems: "center", gap: 10,
          }}>
            <div style={{ display: "flex", gap: 6 }}>
              <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#ff5f57" }} />
              <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#febc2e" }} />
              <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#28c840" }} />
            </div>
            <span style={{ fontSize: 11, color: "#8890a4", fontFamily: "monospace" }}>
              claude — schema-only generation
            </span>
            <div style={{ marginLeft: "auto", display: "flex", gap: 8 }}>
              <Badge color={colors.green} bg={colors.greenSoft}>schema only</Badge>
              <Badge color={colors.cyan} bg={colors.cyanSoft}>no instructions</Badge>
            </div>
          </div>
          <div style={{
            border: `1px solid ${colors.border}`, borderRadius: "0 0 8px 8px",
            background: "#1e2130", padding: 16, minHeight: 120,
          }}>
            <div style={{ marginBottom: 12 }}>
              <span style={{ color: "#6ee7b7", fontFamily: "monospace", fontSize: 13 }}>$ </span>
              <span style={{ color: "#94a3b8", fontFamily: "monospace", fontSize: 13 }}>
                "{DEMO_PAIRS[selectedIdx].prompt}"
              </span>
            </div>
            <pre style={{
              margin: 0, overflow: "auto", fontSize: 13, lineHeight: 1.6,
              color: "#c4cbd8", fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
              maxHeight: 500,
            }}>
              <code>{displayedOutput}</code>
              {isTyping && <span style={{ color: colors.accent, animation: "blink 0.8s infinite" }}>▌</span>}
            </pre>
          </div>
          <style>{`@keyframes blink { 0%, 50% { opacity: 1 } 51%, 100% { opacity: 0 } }`}</style>
        </div>
      )}

      <div style={{
        border: `1px solid ${colors.border}`, borderRadius: 12, padding: 24,
        background: colors.surface, marginTop: 32,
      }}>
        <h3 style={{ fontSize: 15, fontWeight: 600, color: colors.text, margin: "0 0 10px" }}>
          How this works
        </h3>
        <div style={{ fontSize: 13, color: colors.textMuted, lineHeight: 1.7 }}>
          <p style={{ margin: "0 0 10px" }}>
            These responses were generated by giving Claude the GraphQL schema as its only context. No few-shot examples.
            No system prompt explaining Buffer's domain. No MCP tool definitions. Just the type system with its annotations.
          </p>
          <p style={{ margin: "0 0 10px" }}>
            The demo is pre-recorded to show that the model correctly identifies which operations to use and how to 
            structure queries. Variable values and IDs are illustrative. The key takeaway is operation selection, not runtime execution.
          </p>
          <p style={{ margin: 0 }}>
            This is the core thesis: <strong style={{ color: colors.text }}>well-annotated schemas eliminate the need for thick
            adapter layers between APIs and AI agents.</strong> The investment in good descriptions pays dividends across
            every consumption channel: docs, IDEs, and AI agents.
          </p>
        </div>
      </div>
    </div>
  );
}

// ─── MAIN APP ────────────────────────────────────────────────────────────────
export default function App() {
  const [page, setPage] = useState("landing");
  const [sidebarOpen, setSidebarOpen] = useState(true);

  const nav = [
    { key: "landing", label: "Overview", icon: "◈" },
    { key: "quickstart", label: "Quickstart", icon: "▸" },
    { key: "errors", label: "Errors", icon: "⚠" },
    { key: "workflows", label: "Workflows", icon: "⟳" },
    { key: "reference", label: "API Reference", icon: "⬡" },
    { key: "mcp", label: "MCP Server", icon: "🔌" },
    { key: "design", label: "Annotations", icon: "◇" },
    { key: "ai", label: "AI Preview", icon: "✦" },
  ];

  const renderPage = () => {
    switch (page) {
      case "landing": return <LandingPage onNavigate={setPage} />;
      case "reference": return <APIReferencePage />;
      case "mcp": return <MCPServerPage />;
      case "ai": return <AIPage />;
      default: return <DocsPage docKey={page} />;
    }
  };

  return (
    <div style={{
      display: "flex", minHeight: "100vh", fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif",
      background: colors.bg, color: colors.text,
    }}>
      {/* Sidebar */}
      <nav style={{
        width: sidebarOpen ? 200 : 0, minHeight: "100vh", borderRight: `1px solid ${colors.border}`,
        background: colors.surface, padding: sidebarOpen ? "20px 10px" : 0, overflow: "hidden",
        transition: "all 0.2s", flexShrink: 0,
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "0 4px 20px", borderBottom: `1px solid ${colors.border}`, marginBottom: 16 }}>
          <div style={{
            width: 24, height: 24, borderRadius: 5, background: colors.accent,
            display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 700, color: "#fff",
          }}>B</div>
          <span style={{ fontSize: 13, fontWeight: 600, color: colors.text }}>DevEx Kit</span>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
          {nav.map(item => (
            <NavItem
              key={item.key}
              label={item.label}
              icon={item.icon}
              active={page === item.key}
              onClick={() => setPage(item.key)}
            />
          ))}
        </div>
        <div style={{ marginTop: "auto", padding: "20px 4px 0", borderTop: `1px solid ${colors.border}`, position: "absolute", bottom: 20, left: 10, right: 10 }}>
          <a href="https://github.com" target="_blank" rel="noopener" style={{
            fontSize: 12, color: colors.textDim, textDecoration: "none",
            display: "flex", alignItems: "center", gap: 6,
          }}>
            ↗ View on GitHub
          </a>
        </div>
      </nav>

      {/* Main content */}
      <main style={{ flex: 1, overflowY: "auto", minHeight: "100vh" }}>
        {/* Top bar */}
        <div style={{
          position: "sticky", top: 0, zIndex: 10, display: "flex", alignItems: "center",
          padding: "10px 20px", background: `${colors.bg}f0`, backdropFilter: "blur(12px)",
          boxShadow: "0 1px 0 rgba(0,0,0,0.06)",
        }}>
          <button onClick={() => setSidebarOpen(!sidebarOpen)} style={{
            background: "none", border: "none", color: colors.textMuted, cursor: "pointer",
            fontSize: 16, padding: 4, marginRight: 12,
          }}>
            {sidebarOpen ? "◁" : "▷"}
          </button>
          <span style={{ fontSize: 12, color: colors.textDim }}>
            {nav.find(n => n.key === page)?.label || ""}
          </span>
          <span style={{
            marginLeft: "auto", fontSize: 11, color: colors.textDim, padding: "3px 8px",
            border: `1px solid ${colors.border}`, borderRadius: 4,
          }}>
            Proof of Concept
          </span>
        </div>
        {renderPage()}
      </main>
    </div>
  );
}
